spring:
  data:
    cassandra:
      contact-points: 192.168.0.105
      port: 9042
      keyspace-name: simple_crud
      #      username: cassandra
      #      password: cassandra
      schema-act: create_if_not_exists

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html