

spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: simple_crud
      username: cassandra
      password: cassandra

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html